import React from 'react';
import { createRoot } from 'react-dom/client';
import { Canvas } from '@react-three/fiber';
import { OrbitControls } from '@react-three/drei';
import { createClient } from '@supabase/supabase-js';
import './style.css';

type Config={h:number;w:number;d:number;mdf:number;shelves:number;doors:number;margin:number;profile:string;glass:string;hinge:string};
type ParamRow={id:string;estrutura_slug:string;grupo:string;chave:string;nome:string;tipo:'number'|'text'|'boolean'|'select';unidade:string|null;valor_num:number|null;valor_text:string|null;valor_bool:boolean|null;opcoes:any;descricao:string|null;ordem:number;editavel:boolean};
const SUPABASE_URL=(import.meta as any).env?.VITE_SUPABASE_URL || 'https://uyssmueddxtylajnmxad.supabase.co';
const SUPABASE_KEY=(import.meta as any).env?.VITE_SUPABASE_ANON_KEY || 'sb_publishable_YVwgZbFAqi5M4N1i-Iwgdg_7GTzwxrw';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const pp:Record<string,number>={'1036':19,'070':18,'3545':22,'3446':24};
const gp:Record<string,number>={incolor:120,espelho_prata:180,reflecta_bronze:230,reflecta_prata:220,fume:170};
const fallback:Record<string,number|boolean>={cristaleira_altura_padrao:2200,cristaleira_largura_padrao:1000,cristaleira_profundidade_padrao:450,cristaleira_mdf_padrao:18,cristaleira_prateleiras_padrao:4,cristaleira_portas_padrao:2,cristaleira_margem_padrao:45,mdf_preco_m2:115,curva_desconta_mdf:false,curva_desconto_altura:0,curva_desconto_largura:0,curva_desconto_por_porta:1.5,reta_desconta_mdf:true,reta_desconto_altura:3,reta_desconto_largura:3,reta_desconto_por_porta:1.5,porta_perda_percentual:10,porta_mao_obra:35,porta_kit_montagem:4.84,baguete_preco_m:1.2,vidro_espessura_padrao:4};
function num(rows:ParamRow[],key:string){const v=rows.find(x=>x.chave===key)?.valor_num;return Number(v ?? fallback[key] ?? 0)}
function bool(rows:ParamRow[],key:string){const v=rows.find(x=>x.chave===key)?.valor_bool;return Boolean(v ?? fallback[key] ?? false)}
function calc(c:Config,rows:ParamRow[]){const inside=c.hinge==='reta';const prefix=inside?'reta':'curva';const descontaMdf=bool(rows,`${prefix}_desconta_mdf`);const baseW=c.w-(descontaMdf?c.mdf*2:0);const baseH=c.h-(descontaMdf?c.mdf*2:0);const hingeW=num(rows,`${prefix}_desconto_largura`);const hingeH=num(rows,`${prefix}_desconto_altura`);const gap=num(rows,`${prefix}_desconto_por_porta`);const perda=1+num(rows,'porta_perda_percentual')/100;const dw=((baseW-hingeW)/c.doors)-(c.doors>1?gap:0);const dh=baseH-hingeH;const uw=c.w-c.mdf*2;const uh=c.h-c.mdf*2;const ga=(dw/1000)*(dh/1000)*c.doors*perda;const pm=((dw/1000)*2+(dh/1000)*2)*c.doors*perda;const ma=(c.h/1000*c.d/1000*2)+(c.w/1000*c.d/1000*2)+(uw/1000*(c.d-c.mdf)/1000*c.shelves);const cost=ga*gp[c.glass]+pm*pp[c.profile]+ma*num(rows,'mdf_preco_m2')+pm*num(rows,'baguete_preco_m')+c.doors*num(rows,'porta_kit_montagem')+c.doors*num(rows,'porta_mao_obra')+80;return{uw,uh,baseW,baseH,dw,dh,ga,pm,ma,cost,sale:cost/(1-c.margin/100),sideGap:gap/2,displayGap:gap,mdfDiscount:descontaMdf?c.mdf*2:0,hingeW,hingeH,gapPerDoor:gap,perda}}
function App(){
 const[c,setC]=React.useState<Config>({h:2200,w:1000,d:450,mdf:18,shelves:4,doors:2,margin:45,profile:'1036',glass:'reflecta_bronze',hinge:'curva'});
 const[rows,setRows]=React.useState<ParamRow[]>([]);const[status,setStatus]=React.useState('Carregando parâmetros...');
 const[moveisOpen,setMoveisOpen]=React.useState(false);const[hasCristaleira,setHasCristaleira]=React.useState(false);const[resultadoOpen,setResultadoOpen]=React.useState(false);const[paramsOpen,setParamsOpen]=React.useState(false);const loaded=React.useRef(false);
 React.useEffect(()=>{async function load(){const {data,error}=await supabase.from('promob_parametros').select('*').order('estrutura_slug').order('ordem');if(error){setStatus('Erro ao carregar Supabase. Usando padrão local.');return}const paramRows=(data||[]) as ParamRow[];setRows(paramRows);setStatus('Parâmetros conectados ao Supabase.');if(!loaded.current){loaded.current=true;setC(x=>({...x,h:num(paramRows,'cristaleira_altura_padrao'),w:num(paramRows,'cristaleira_largura_padrao'),d:num(paramRows,'cristaleira_profundidade_padrao'),mdf:num(paramRows,'cristaleira_mdf_padrao'),shelves:num(paramRows,'cristaleira_prateleiras_padrao'),doors:num(paramRows,'cristaleira_portas_padrao'),margin:num(paramRows,'cristaleira_margem_padrao')}))}}load()},[]);
 const r=calc(c,rows);const n=(k:keyof Config)=>(e:React.ChangeEvent<HTMLInputElement>)=>setC({...c,[k]:Number(e.target.value)});const s=(k:keyof Config)=>(e:React.ChangeEvent<HTMLSelectElement>)=>setC({...c,[k]:e.target.value});
 const saveRows=async()=>{setStatus('Salvando parâmetros...');const payload=rows.map(({id,created_at,updated_at,...x}:any)=>x);const {error}=await supabase.from('promob_parametros').upsert(payload,{onConflict:'chave'});setStatus(error?'Erro ao salvar parâmetros.':'Parâmetros salvos no Supabase.');};
 const left=moveisOpen?390:64;const right=resultadoOpen?340:64;
 return <main className="app" style={{gridTemplateColumns:`${left}px 1fr ${right}px`}}><aside className="side leftSide"><button className="flag" onClick={()=>setMoveisOpen(!moveisOpen)}>Móveis</button>{moveisOpen&&<div className="sideBody"><h2 className="menuTitle">Estruturas</h2>{!hasCristaleira?<button className="addBtn" onClick={()=>setHasCristaleira(true)}>Cristaleira +</button>:<CristaleiraForm c={c} n={n} s={s}/>}<button className="groupTitle" onClick={()=>setParamsOpen(!paramsOpen)}>Parâmetros {paramsOpen?'−':'+'}</button>{paramsOpen&&<Parametros rows={rows} setRows={setRows} saveRows={saveRows} status={status}/>}</div>}</aside><section className="workspace"><div className="scene">{hasCristaleira?<Canvas camera={{position:[1.8,1.2,2.2],fov:45}}><ambientLight intensity={0.8}/><directionalLight position={[3,4,5]}/><Cab c={c} r={r}/><OrbitControls/></Canvas>:<div className="empty"><h2>Nenhuma estrutura adicionada</h2><p>Clique em Móveis e depois em Cristaleira + para começar.</p></div>}</div></section><aside className="side rightSide"><button className="flag rightFlag" onClick={()=>setResultadoOpen(!resultadoOpen)}>Resultado</button>{resultadoOpen&&<Resultado has={hasCristaleira} c={c} r={r}/>}</aside></main>
}
function CristaleiraForm({c,n,s}:{c:Config;n:(k:keyof Config)=>(e:React.ChangeEvent<HTMLInputElement>)=>void;s:(k:keyof Config)=>(e:React.ChangeEvent<HTMLSelectElement>)=>void}){return <div className="formBox"><h2>Cristaleira</h2><F l="Altura" v={c.h} f={n('h')}/><F l="Largura" v={c.w} f={n('w')}/><F l="Profundidade" v={c.d} f={n('d')}/><F l="MDF" v={c.mdf} f={n('mdf')}/><F l="Prateleiras" v={c.shelves} f={n('shelves')}/><F l="Portas" v={c.doors} f={n('doors')}/><F l="Margem" v={c.margin} f={n('margin')}/><label>Dobradiça<select value={c.hinge} onChange={s('hinge')}><option value="curva">Curva - porta por fora do vão</option><option value="reta">Reta - porta por dentro do vão</option></select></label><label>Perfil<select value={c.profile} onChange={s('profile')}><option value="1036">1036</option><option value="070">070</option><option value="3545">3545</option><option value="3446">3446</option></select></label><label>Vidro<select value={c.glass} onChange={s('glass')}><option value="incolor">Incolor</option><option value="espelho_prata">Espelho prata</option><option value="reflecta_bronze">Reflecta bronze</option><option value="reflecta_prata">Reflecta prata</option><option value="fume">Fume</option></select></label></div>}
function Parametros({rows,setRows,saveRows,status}:{rows:ParamRow[];setRows:React.Dispatch<React.SetStateAction<ParamRow[]>>;saveRows:()=>void;status:string}){const edit=(id:string,val:string|boolean)=>setRows(rs=>rs.map(r=>r.id===id?{...r,valor_num:r.tipo==='number'?Number(val):r.valor_num,valor_text:r.tipo==='text'||r.tipo==='select'?String(val):r.valor_text,valor_bool:r.tipo==='boolean'?Boolean(val):r.valor_bool}:r));const groups=[...new Set(rows.map(r=>r.estrutura_slug))];return <div className="params"><div className="status">{status}</div>{groups.map(g=><div className="paramCard" key={g}><h3>{g==='porta_aluminio'?'Porta de alumínio':'Cristaleira'}</h3>{rows.filter(r=>r.estrutura_slug===g).map(r=><label className="paramEdit" key={r.id}><span>{r.nome}{r.unidade?` (${r.unidade})`:''}</span>{r.tipo==='boolean'?<select value={String(r.valor_bool)} onChange={e=>edit(r.id,e.target.value==='true')}><option value="true">Sim</option><option value="false">Não</option></select>:<input type={r.tipo==='number'?'number':'text'} step="0.01" value={r.tipo==='number'?String(r.valor_num??''):String(r.valor_text??'')} onChange={e=>edit(r.id,e.target.value)}/>}<small>{r.descricao}</small></label>)}</div>)}<button className="saveBtn" onClick={saveRows}>Salvar parâmetros</button></div>}
function Resultado({has,c,r}:{has:boolean;c:Config;r:ReturnType<typeof calc>}){return <div className="sideBody resultBody">{has?<><h2>Resultado</h2><p>Medida móvel: {c.h} x {c.w} mm</p><p>Dobradiça: {c.hinge==='reta'?'reta, porta por dentro':'curva, porta por fora'}</p><p>Base porta: {Math.round(r.baseH)} x {Math.round(r.baseW)} mm</p><p>Cada porta: {r.dh.toFixed(1)} x {r.dw.toFixed(1)} mm</p><p>Descontos: MDF {r.mdfDiscount} mm / dobradiça {r.hingeH} mm alt e {r.hingeW} mm larg / portas {r.gapPerDoor} mm por porta</p><p>Vidro: {r.ga.toFixed(2)} m²</p><p>Perfil: {r.pm.toFixed(2)} m</p><p>MDF: {r.ma.toFixed(2)} m²</p><p>Custo: R$ {r.cost.toFixed(2)}</p><p>Venda: R$ {r.sale.toFixed(2)}</p></>:<p>Adicione uma estrutura primeiro.</p>}</div>}
function F(p:{l:string;v:number;f:(e:React.ChangeEvent<HTMLInputElement>)=>void}){return <label>{p.l}<input type="number" value={p.v} onChange={p.f}/></label>}
function Cab({c,r}:{c:Config;r:ReturnType<typeof calc>}){const w=c.w/1000,h=c.h/1000,d=c.d/1000,m=c.mdf/1000,uw=r.uw/1000,uh=r.uh/1000,bw=r.baseW/1000,dw=r.dw/1000,dh=r.dh/1000,side=r.sideGap/1000,gap=r.displayGap/1000;return <group position={[0,h/2,0]}><B p={[-w/2+m/2,0,0]} z={[m,h,d]} color="#7a5232"/><B p={[w/2-m/2,0,0]} z={[m,h,d]} color="#7a5232"/><B p={[0,h/2-m/2,0]} z={[w,m,d]} color="#7a5232"/><B p={[0,-h/2+m/2,0]} z={[w,m,d]} color="#7a5232"/>{Array.from({length:c.shelves}).map((_,i)=><B key={i} p={[0,-uh/2+(i+1)*uh/(c.shelves+1),0]} z={[uw,m,d-m]} color="#8b623e"/>)}{Array.from({length:c.doors}).map((_,i)=><Door key={i} x={-bw/2+side+dw/2+i*(dw+gap)} w={dw} h={dh} z={d/2+0.02}/>)}</group>}
function Door({x,w,h,z}:{x:number;w:number;h:number;z:number}){const b=.035;return <group position={[x,0,z]}><B p={[0,0,0]} z={[w-b*2,h-b*2,.01]} color="#7f5a35" opacity={.45}/><B p={[0,h/2-b/2,.01]} z={[w,b,.03]} color="#050505"/><B p={[0,-h/2+b/2,.01]} z={[w,b,.03]} color="#050505"/><B p={[-w/2+b/2,0,.01]} z={[b,h,.03]} color="#050505"/><B p={[w/2-b/2,0,.01]} z={[b,h,.03]} color="#050505"/></group>}
function B({p,z,color,opacity=1}:{p:[number,number,number];z:[number,number,number];color:string;opacity?:number}){return <mesh position={p}><boxGeometry args={z}/><meshStandardMaterial color={color} transparent={opacity<1} opacity={opacity}/></mesh>}
createRoot(document.getElementById('root') as HTMLElement).render(<React.StrictMode><App/></React.StrictMode>);
