import React from 'react';
import { createRoot } from 'react-dom/client';
import { Canvas } from '@react-three/fiber';
import { OrbitControls } from '@react-three/drei';
import { createClient } from '@supabase/supabase-js';
import './style.css';

type Config={h:number;w:number;d:number;mdf:number;shelves:number;doors:number;margin:number;profile:string;glass:string;hinge:string};
type Amb={w:number;d:number;h:number;floor:string;back:boolean;left:boolean;right:boolean};
type WindowData={w:number;h:number;fromFloor:number;glass:boolean;frame:boolean;opening:string};
type CounterData={w:number;d:number;thick:number;fromFloor:number;wetW:number;depthFromWall:number;sink:boolean;faucet:boolean};
type ClosetData={w:number;d:number;h:number;modules:number;shelves:number;sideType:string;backGlass:boolean;doors:boolean;led:boolean};
type BaseObj={id:string;type:'window'|'countertop'|'closet'|'cristaleira';name:string;x:number;y:number;z:number;rotation:number;visible:boolean;locked:boolean};
type WindowObj=BaseObj&{type:'window';data:WindowData};
type CounterObj=BaseObj&{type:'countertop';data:CounterData};
type ClosetObj=BaseObj&{type:'closet';data:ClosetData};
type CristaleiraObj=BaseObj&{type:'cristaleira';data:Config};
type ProjectObject=WindowObj|CounterObj|ClosetObj|CristaleiraObj;
type ParamRow={id:string;estrutura_slug:string;grupo:string;chave:string;nome:string;tipo:'number'|'text'|'boolean'|'select';unidade:string|null;valor_num:number|null;valor_text:string|null;valor_bool:boolean|null;opcoes:any;descricao:string|null;ordem:number;editavel:boolean};
type ColorProfile={id:string;nome:string;custo:number|null;margem:number|null;perda:number|null;preco:number|null;insumos:string[]|null;tipologias:string[]|null;tags:string[]|null};
type ColorMaterial={id:number;nome:string|null;custo:number|null;tipo_medida:string|null;margem:number|null;preco:number|null;perda:number|null;tag:string|null};
const MOBIL_URL=(import.meta as any).env?.VITE_SUPABASE_URL || 'https://uyssmueddxtylajnmxad.supabase.co';
const MOBIL_KEY=(import.meta as any).env?.VITE_SUPABASE_ANON_KEY || 'sb_publishable_YVwgZbFAqi5M4N1i-Iwgdg_7GTzwxrw';
const COLOR_URL=(import.meta as any).env?.VITE_COLOR_SUPABASE_URL || 'https://hfhwvzldhgqniqnurync.supabase.co';
const COLOR_KEY=(import.meta as any).env?.VITE_COLOR_SUPABASE_ANON_KEY || 'sb_publishable_0j-jqB63odD2yvugj7olMA_s18OwuPl';
const supabase=createClient(MOBIL_URL,MOBIL_KEY);
const colorDb=createClient(COLOR_URL,COLOR_KEY);
const gp:Record<string,number>={incolor:120,espelho_prata:180,reflecta_bronze:230,reflecta_prata:220,fume:170};
const fallback:Record<string,number|boolean>={cristaleira_altura_padrao:2200,cristaleira_largura_padrao:1000,cristaleira_profundidade_padrao:450,cristaleira_mdf_padrao:18,cristaleira_prateleiras_padrao:4,cristaleira_portas_padrao:2,cristaleira_margem_padrao:45,mdf_preco_m2:115,curva_desconta_mdf:false,curva_desconto_altura:0,curva_desconto_largura:0,curva_desconto_por_porta:1.5,reta_desconta_mdf:true,reta_desconto_altura:3,reta_desconto_largura:3,reta_desconto_por_porta:1.5,porta_perda_percentual:10,porta_mao_obra:35,porta_kit_montagem:4.84,baguete_preco_m:1.2,vidro_espessura_padrao:4};
const defaultCristaleira:Config={h:2200,w:1000,d:450,mdf:18,shelves:4,doors:2,margin:45,profile:'',glass:'reflecta_bronze',hinge:'curva'};
function num(rows:ParamRow[],key:string){const v=rows.find(x=>x.chave===key)?.valor_num;return Number(v ?? fallback[key] ?? 0)}
function bool(rows:ParamRow[],key:string){const v=rows.find(x=>x.chave===key)?.valor_bool;return Boolean(v ?? fallback[key] ?? false)}
function findMat(ms:ColorMaterial[],term:string){return ms.find(m=>(m.nome||'').toLowerCase().includes(term.toLowerCase()))}
function brl(n:number){return `R$ ${n.toFixed(2)}`}
function calc(c:Config,rows:ParamRow[],profiles:ColorProfile[],materials:ColorMaterial[]){const inside=c.hinge==='reta';const prefix=inside?'reta':'curva';const descontaMdf=bool(rows,`${prefix}_desconta_mdf`);const baseW=c.w-(descontaMdf?c.mdf*2:0);const baseH=c.h-(descontaMdf?c.mdf*2:0);const hingeW=num(rows,`${prefix}_desconto_largura`);const hingeH=num(rows,`${prefix}_desconto_altura`);const gap=num(rows,`${prefix}_desconto_por_porta`);const perda=1+num(rows,'porta_perda_percentual')/100;const dw=((baseW-hingeW)/c.doors)-(c.doors>1?gap:0);const dh=baseH-hingeH;const uw=c.w-c.mdf*2;const uh=c.h-c.mdf*2;const selected=profiles.find(p=>p.id===c.profile);const profileCost=Number(selected?.custo ?? 19);const ba02=Number(findMat(materials,'BA02')?.custo ?? num(rows,'baguete_preco_m'));const cant=Number(findMat(materials,'cantoneira')?.custo ?? num(rows,'porta_kit_montagem'));const ga=(dw/1000)*(dh/1000)*c.doors*perda;const pm=((dw/1000)*2+(dh/1000)*2)*c.doors*perda;const ma=(c.h/1000*c.d/1000*2)+(c.w/1000*c.d/1000*2)+(uw/1000*(c.d-c.mdf)/1000*c.shelves);const cantCost=c.doors*4*cant;const cost=ga*gp[c.glass]+pm*profileCost+ma*num(rows,'mdf_preco_m2')+pm*ba02+cantCost+c.doors*num(rows,'porta_mao_obra')+80;return{uw,uh,baseW,baseH,dw,dh,ga,pm,ma,cost,sale:cost/(1-c.margin/100),sideGap:gap/2,displayGap:gap,mdfDiscount:descontaMdf?c.mdf*2:0,hingeW,hingeH,gapPerDoor:gap,perda,profileCost,ba02,cant,cantCost,profileName:selected?.nome||'1036 padrão'}}
function closetCalc(cl:ClosetData){const mw=cl.w/Math.max(cl.modules,1);const vertical=(cl.modules+1)*cl.h/1000;const baseTop=2*((cl.w/1000)*2+(cl.d/1000)*2);const shelves=cl.modules*cl.shelves*(mw/1000);const glassBack=cl.backGlass?(cl.w/1000)*(cl.h/1000):0;const glassSides=2*(cl.d/1000)*(cl.h/1000);const glassDoors=cl.doors?(cl.w/1000)*(cl.h/1000):0;return{mw,vertical,baseTop,shelves,totalProfile:vertical+baseTop+shelves,glassArea:glassBack+glassSides+glassDoors}}
function mk(type:ProjectObject['type'],name:string,data:any,x=0,z=0):ProjectObject{return{id:`${type}-${Date.now()}-${Math.round(Math.random()*999)}`,type,name,x,y:0,z,rotation:0,visible:true,locked:false,data} as ProjectObject}
function dims(o:ProjectObject){if(o.type==='window')return{w:o.data.w,h:o.data.h,d:30};if(o.type==='countertop')return{w:o.data.w,h:o.data.thick,d:o.data.d};if(o.type==='closet')return{w:o.data.w,h:o.data.h,d:o.data.d};return{w:o.data.w,h:o.data.h,d:o.data.d}}
function App(){
 const[amb,setAmb]=React.useState<Amb>({w:3200,d:2800,h:2700,floor:'porcelanato claro',back:true,left:true,right:false});
 const[objects,setObjects]=React.useState<ProjectObject[]>([]);const[selectedId,setSelectedId]=React.useState<string|null>('environment');
 const[rows,setRows]=React.useState<ParamRow[]>([]);const[profiles,setProfiles]=React.useState<ColorProfile[]>([]);const[materials,setMaterials]=React.useState<ColorMaterial[]>([]);const[status,setStatus]=React.useState('Carregando parâmetros...');const[colorStatus,setColorStatus]=React.useState('Carregando ColorGlass...');
 const[menuOpen,setMenuOpen]=React.useState(false);const[ambOpen,setAmbOpen]=React.useState(true);const[paramsOpen,setParamsOpen]=React.useState(false);const[propsOpen,setPropsOpen]=React.useState(true);const[resultadoOpen,setResultadoOpen]=React.useState(false);const colorLoaded=React.useRef(false);
 React.useEffect(()=>{async function load(){const {data,error}=await supabase.from('promob_parametros').select('*').order('estrutura_slug').order('ordem');if(error){setStatus('Erro ao carregar Supabase. Usando padrão local.');return}setRows((data||[]) as ParamRow[]);setStatus('Parâmetros conectados ao Supabase.')}load()},[]);
 React.useEffect(()=>{async function loadColor(){const {data:p,error:pe}=await colorDb.from('perfis').select('id,nome,custo,margem,perda,preco,insumos,tipologias,tags').ilike('nome','%1036%').order('nome');const {data:m,error:me}=await colorDb.from('materiais').select('id,nome,custo,tipo_medida,margem,preco,perda,tag').order('nome');if(pe||me){setColorStatus('Erro ao ler banco ColorGlass. Usando custos fallback.');return}const prof=(p||[]) as ColorProfile[];const mats=((m||[]) as ColorMaterial[]).filter(x=>{const n=(x.nome||'').toLowerCase();return n.includes('ba02')||n.includes('cantoneira 50')||n.includes('baguete')});setProfiles(prof);setMaterials(mats);setColorStatus(`ColorGlass conectado: ${prof.length} perfis 1036 e ${mats.length} insumos lidos.`);if(!colorLoaded.current&&prof[0]){colorLoaded.current=true;setObjects(os=>os.map(o=>o.type==='cristaleira'?{...o,data:{...o.data,profile:prof[0].id}}:o))}}loadColor()},[]);
 const selected=selectedId==='environment'?null:objects.find(o=>o.id===selectedId)||null;
 const updateObj=(id:string,patch:Partial<ProjectObject>)=>setObjects(os=>os.map(o=>o.id===id?{...o,...patch} as ProjectObject:o));
 const updateData=(id:string,patch:any)=>setObjects(os=>os.map(o=>o.id===id?{...o,data:{...o.data,...patch}} as ProjectObject:o));
 const addObj=(o:ProjectObject)=>{setObjects(os=>[...os,o]);setSelectedId(o.id);setPropsOpen(true)};
 const addWindow=()=>addObj(mk('window','Janela',{w:1200,h:1000,fromFloor:900,glass:true,frame:true,opening:'fixa'},0,-amb.d/2+35));
 const addCounter=()=>addObj(mk('countertop','Bancada / área molhada',{w:2400,d:600,thick:20,fromFloor:900,wetW:800,depthFromWall:40,sink:true,faucet:true},0,0));
 const addCloset=()=>addObj(mk('closet','Closet Evidence',{w:2600,d:520,h:2400,modules:4,shelves:3,sideType:'9577 externo',backGlass:true,doors:true,led:true},0,0));
 const addCristaleira=()=>addObj(mk('cristaleira','Cristaleira',{...defaultCristaleira,h:num(rows,'cristaleira_altura_padrao')||2200,w:num(rows,'cristaleira_largura_padrao')||1000,d:num(rows,'cristaleira_profundidade_padrao')||450,mdf:num(rows,'cristaleira_mdf_padrao')||18,shelves:num(rows,'cristaleira_prateleiras_padrao')||4,doors:num(rows,'cristaleira_portas_padrao')||2,margin:num(rows,'cristaleira_margem_padrao')||45,profile:profiles[0]?.id||''},0,0));
 const deleteObj=()=>{if(!selected)return;setObjects(os=>os.filter(o=>o.id!==selected.id));setSelectedId('environment')};
 const duplicateObj=()=>{if(!selected)return;const copy={...selected,id:`${selected.type}-${Date.now()}`,name:`${selected.name} cópia`,x:selected.x+120,data:{...selected.data}} as ProjectObject;addObj(copy)};
 const movePreset=(mode:string)=>{if(!selected)return;const d=dims(selected);if(mode==='center')updateObj(selected.id,{x:0,z:0} as any);if(mode==='back')updateObj(selected.id,{z:-amb.d/2+d.d/2+40} as any);if(mode==='left')updateObj(selected.id,{x:-amb.w/2+d.w/2+40} as any);if(mode==='right')updateObj(selected.id,{x:amb.w/2-d.w/2-40} as any);};
 const saveRows=async()=>{setStatus('Salvando parâmetros...');const payload=rows.map(({id,created_at,updated_at,...x}:any)=>x);const {error}=await supabase.from('promob_parametros').upsert(payload,{onConflict:'chave'});setStatus(error?'Erro ao salvar parâmetros.':'Parâmetros salvos no Supabase.')};
 const left=menuOpen?430:64;const right=resultadoOpen?380:64;
 return <main className="app" style={{gridTemplateColumns:`${left}px 1fr ${right}px`}}><aside className="side leftSide"><button className="flag" onClick={()=>setMenuOpen(!menuOpen)}>Projeto</button>{menuOpen&&<div className="sideBody"><button className="groupTitle" onClick={()=>setAmbOpen(!ambOpen)}>Ambiente {ambOpen?'−':'+'}</button>{ambOpen&&<AmbienteForm amb={amb} setAmb={setAmb} addWindow={addWindow}/>}<button className="groupTitle" onClick={()=>setPropsOpen(!propsOpen)}>Objeto selecionado {propsOpen?'−':'+'}</button>{propsOpen&&<ObjectProps selectedId={selectedId} selected={selected} amb={amb} setAmb={setAmb} updateObj={updateObj} updateData={updateData} duplicateObj={duplicateObj} deleteObj={deleteObj} movePreset={movePreset}/>}<ObjectList objects={objects} selectedId={selectedId} setSelectedId={setSelectedId}/><div className="helpBox"><b>Navegação 3D</b><span>Scroll: zoom</span><span>Botão esquerdo: girar</span><span>Botão direito: mover</span></div><h2 className="menuTitle">Estruturas</h2><button className="addBtn" onClick={addCounter}>Bancada / área molhada +</button><button className="addBtn" onClick={addCloset}>Closet Evidence +</button><button className="addBtn" onClick={addCristaleira}>Cristaleira +</button><button className="groupTitle" onClick={()=>setParamsOpen(!paramsOpen)}>Parâmetros globais {paramsOpen?'−':'+'}</button>{paramsOpen&&<Parametros rows={rows} setRows={setRows} saveRows={saveRows} status={status}/>}</div>}</aside><section className="workspace"><div className="scene"><Canvas camera={{position:[2.8,2.0,3.5],fov:45}} onPointerMissed={()=>setSelectedId(null)}><ambientLight intensity={0.85}/><directionalLight position={[3,4,5]}/><Env3D amb={amb} selected={selectedId==='environment'} onSelect={()=>setSelectedId('environment')}/>{objects.map(o=><Object3D key={o.id} obj={o} selected={selectedId===o.id} onSelect={()=>setSelectedId(o.id)} amb={amb} rows={rows} profiles={profiles} materials={materials}/>) }<OrbitControls/></Canvas>{objects.length===0&&<div className="canvasHint"><h2>Ambiente criado</h2><p>Use Janela +, Bancada +, Closet + ou Cristaleira + para inserir objetos.</p></div>}</div></section><aside className="side rightSide"><button className="flag rightFlag" onClick={()=>setResultadoOpen(!resultadoOpen)}>Resultado</button>{resultadoOpen&&<Resultado amb={amb} objects={objects} rows={rows} profiles={profiles} materials={materials} colorStatus={colorStatus}/>}</aside></main>}
function AmbienteForm({amb,setAmb,addWindow}:{amb:Amb;setAmb:React.Dispatch<React.SetStateAction<Amb>>;addWindow:()=>void}){const n=(k:'w'|'d'|'h')=>(e:React.ChangeEvent<HTMLInputElement>)=>setAmb({...amb,[k]:Number(e.target.value)});return <div className="formBox"><h2>Ambiente</h2><F l="Largura ambiente" v={amb.w} f={n('w')}/><F l="Profundidade ambiente" v={amb.d} f={n('d')}/><F l="Pé-direito" v={amb.h} f={n('h')}/><label>Material do piso<input value={amb.floor} onChange={e=>setAmb({...amb,floor:e.target.value})}/></label><label className="checkLine"><input type="checkbox" checked={amb.back} onChange={e=>setAmb({...amb,back:e.target.checked})}/> Parede fundo</label><label className="checkLine"><input type="checkbox" checked={amb.left} onChange={e=>setAmb({...amb,left:e.target.checked})}/> Parede esquerda</label><label className="checkLine"><input type="checkbox" checked={amb.right} onChange={e=>setAmb({...amb,right:e.target.checked})}/> Parede direita</label><button className="addBtn" onClick={addWindow}>Janela +</button></div>}
function ObjectList({objects,selectedId,setSelectedId}:{objects:ProjectObject[];selectedId:string|null;setSelectedId:(id:string)=>void}){return <div className="paramCard"><h3>Objetos do projeto</h3><button className={selectedId==='environment'?'miniBtn active':'miniBtn'} onClick={()=>setSelectedId('environment')}>Ambiente</button>{objects.map(o=><button key={o.id} className={selectedId===o.id?'miniBtn active':'miniBtn'} onClick={()=>setSelectedId(o.id)}>{o.visible?'':'[oculto] '}{o.name}</button>)}</div>}
function ObjectProps({selectedId,selected,amb,setAmb,updateObj,updateData,duplicateObj,deleteObj,movePreset}:{selectedId:string|null;selected:ProjectObject|null;amb:Amb;setAmb:(a:Amb)=>void;updateObj:(id:string,p:Partial<ProjectObject>)=>void;updateData:(id:string,p:any)=>void;duplicateObj:()=>void;deleteObj:()=>void;movePreset:(m:string)=>void}){if(selectedId==='environment')return <div className="objectBox"><h2>Ambiente selecionado</h2><AmbienteForm amb={amb} setAmb={setAmb as any} addWindow={()=>{}}/></div>;if(!selected)return <div className="objectBox"><p>Nenhum objeto selecionado.</p></div>;const setBase=(k:'name'|'x'|'y'|'z'|'rotation')=>(e:any)=>updateObj(selected.id,{[k]:k==='name'?e.target.value:Number(e.target.value)} as any);return <div className="objectBox"><h2>{selected.name}</h2><label>Nome<input value={selected.name} onChange={setBase('name')}/></label><F l="Posição X" v={selected.x} f={setBase('x')}/><F l="Posição Y" v={selected.y} f={setBase('y')}/><F l="Posição Z" v={selected.z} f={setBase('z')}/><F l="Rotação" v={selected.rotation} f={setBase('rotation')}/><label className="checkLine"><input type="checkbox" checked={selected.visible} onChange={e=>updateObj(selected.id,{visible:e.target.checked} as any)}/> Visível</label><label className="checkLine"><input type="checkbox" checked={selected.locked} onChange={e=>updateObj(selected.id,{locked:e.target.checked} as any)}/> Travado</label>{selected.type==='window'&&<WindowProps obj={selected} updateData={updateData}/>} {selected.type==='countertop'&&<CounterProps obj={selected} updateData={updateData}/>} {selected.type==='closet'&&<ClosetProps obj={selected} updateData={updateData}/>} {selected.type==='cristaleira'&&<CristaleiraProps obj={selected} updateData={updateData}/>}<div className="actionGrid"><button className="miniBtn" onClick={duplicateObj}>Duplicar</button><button className="miniBtn" onClick={()=>updateObj(selected.id,{visible:!selected.visible} as any)}>{selected.visible?'Ocultar':'Mostrar'}</button><button className="miniBtn" onClick={()=>movePreset('center')}>Centralizar</button><button className="miniBtn" onClick={()=>movePreset('back')}>Parede fundo</button><button className="miniBtn" onClick={()=>movePreset('left')}>Parede esquerda</button><button className="miniBtn" onClick={()=>movePreset('right')}>Parede direita</button><button className="miniBtn danger" onClick={deleteObj}>Deletar</button></div></div>}
function WindowProps({obj,updateData}:{obj:WindowObj;updateData:(id:string,p:any)=>void}){const d=obj.data;const n=(k:keyof WindowData)=>(e:any)=>updateData(obj.id,{[k]:typeof d[k]==='number'?Number(e.target.value):e.target.value});return <div><h3>Janela</h3><F l="Largura" v={d.w} f={n('w')}/><F l="Altura" v={d.h} f={n('h')}/><F l="Altura do chão" v={d.fromFloor} f={n('fromFloor')}/><label>Tipo abertura<select value={d.opening} onChange={n('opening')}><option value="fixa">Fixa</option><option value="correr">Correr</option><option value="basculante">Basculante</option><option value="abrir">Abrir</option></select></label><h3>Agregados</h3><label className="checkLine"><input type="checkbox" checked={d.glass} onChange={e=>updateData(obj.id,{glass:e.target.checked})}/> Vidro</label><label className="checkLine"><input type="checkbox" checked={d.frame} onChange={e=>updateData(obj.id,{frame:e.target.checked})}/> Moldura</label></div>}
function CounterProps({obj,updateData}:{obj:CounterObj;updateData:(id:string,p:any)=>void}){const d=obj.data;const n=(k:keyof CounterData)=>(e:any)=>updateData(obj.id,{[k]:typeof d[k]==='number'?Number(e.target.value):e.target.value});return <div><h3>Bancada / área molhada</h3><F l="Largura total" v={d.w} f={n('w')}/><F l="Profundidade" v={d.d} f={n('d')}/><F l="Espessura" v={d.thick} f={n('thick')}/><F l="Altura do chão" v={d.fromFloor} f={n('fromFloor')}/><F l="Largura área molhada" v={d.wetW} f={n('wetW')}/><F l="Distância da parede" v={d.depthFromWall} f={n('depthFromWall')}/><label className="checkLine"><input type="checkbox" checked={d.sink} onChange={e=>updateData(obj.id,{sink:e.target.checked})}/> Cuba</label><label className="checkLine"><input type="checkbox" checked={d.faucet} onChange={e=>updateData(obj.id,{faucet:e.target.checked})}/> Torneira</label></div>}
function ClosetProps({obj,updateData}:{obj:ClosetObj;updateData:(id:string,p:any)=>void}){const d=obj.data,cl=closetCalc(d);const n=(k:keyof ClosetData)=>(e:any)=>updateData(obj.id,{[k]:typeof d[k]==='number'?Number(e.target.value):e.target.value});return <div><h3>Closet Evidence</h3><F l="Largura" v={d.w} f={n('w')}/><F l="Profundidade" v={d.d} f={n('d')}/><F l="Altura" v={d.h} f={n('h')}/><F l="Módulos" v={d.modules} f={n('modules')}/><F l="Prateleiras por módulo" v={d.shelves} f={n('shelves')}/><label>Tipo lateral<select value={d.sideType} onChange={n('sideType')}><option value="9577 externo">Vidro externo - 9577</option><option value="9571 embutido">Vidro embutido - 9571</option></select></label><label className="checkLine"><input type="checkbox" checked={d.backGlass} onChange={e=>updateData(obj.id,{backGlass:e.target.checked})}/> Fundo vidro</label><label className="checkLine"><input type="checkbox" checked={d.doors} onChange={e=>updateData(obj.id,{doors:e.target.checked})}/> Portas vidro</label><label className="checkLine"><input type="checkbox" checked={d.led} onChange={e=>updateData(obj.id,{led:e.target.checked})}/> LED</label><div className="paramCard"><div className="paramRow"><span>Módulo</span><b>{cl.mw.toFixed(0)} mm</b></div><div className="paramRow"><span>Perfis</span><b>{cl.totalProfile.toFixed(2)} m</b></div><div className="paramRow"><span>Vidro</span><b>{cl.glassArea.toFixed(2)} m²</b></div></div></div>}
function CristaleiraProps({obj,updateData}:{obj:CristaleiraObj;updateData:(id:string,p:any)=>void}){const d=obj.data;const n=(k:keyof Config)=>(e:any)=>updateData(obj.id,{[k]:typeof d[k]==='number'?Number(e.target.value):e.target.value});return <div><h3>Cristaleira</h3><F l="Altura" v={d.h} f={n('h')}/><F l="Largura" v={d.w} f={n('w')}/><F l="Profundidade" v={d.d} f={n('d')}/><F l="MDF" v={d.mdf} f={n('mdf')}/><F l="Prateleiras" v={d.shelves} f={n('shelves')}/><F l="Portas" v={d.doors} f={n('doors')}/><F l="Margem" v={d.margin} f={n('margin')}/><label>Dobradiça<select value={d.hinge} onChange={n('hinge')}><option value="curva">Curva</option><option value="reta">Reta</option></select></label><label>Vidro<select value={d.glass} onChange={n('glass')}><option value="incolor">Incolor</option><option value="espelho_prata">Espelho prata</option><option value="reflecta_bronze">Reflecta bronze</option><option value="reflecta_prata">Reflecta prata</option><option value="fume">Fume</option></select></label></div>}
function Parametros({rows,setRows,saveRows,status}:{rows:ParamRow[];setRows:React.Dispatch<React.SetStateAction<ParamRow[]>>;saveRows:()=>void;status:string}){const edit=(id:string,val:string|boolean)=>setRows(rs=>rs.map(r=>r.id===id?{...r,valor_num:r.tipo==='number'?Number(val):r.valor_num,valor_text:r.tipo==='text'||r.tipo==='select'?String(val):r.valor_text,valor_bool:r.tipo==='boolean'?Boolean(val):r.valor_bool}:r));const groups=[...new Set(rows.map(r=>r.estrutura_slug))];return <div className="params"><div className="status">{status}</div>{groups.map(g=><div className="paramCard" key={g}><h3>{g==='porta_aluminio'?'Porta de alumínio':'Cristaleira'}</h3>{rows.filter(r=>r.estrutura_slug===g).map(r=><label className="paramEdit" key={r.id}><span>{r.nome}{r.unidade?` (${r.unidade})`:''}</span>{r.tipo==='boolean'?<select value={String(r.valor_bool)} onChange={e=>edit(r.id,e.target.value==='true')}><option value="true">Sim</option><option value="false">Não</option></select>:<input type={r.tipo==='number'?'number':'text'} step="0.01" value={r.tipo==='number'?String(r.valor_num??''):String(r.valor_text??'')} onChange={e=>edit(r.id,e.target.value)}/>}<small>{r.descricao}</small></label>)}</div>)}<button className="saveBtn" onClick={saveRows}>Salvar parâmetros</button></div>}
function Resultado({amb,objects,rows,profiles,materials,colorStatus}:{amb:Amb;objects:ProjectObject[];rows:ParamRow[];profiles:ColorProfile[];materials:ColorMaterial[];colorStatus:string}){return <div className="sideBody resultBody"><h2>Resultado</h2><p>Ambiente: {amb.w} x {amb.d} x {amb.h} mm</p><p>Objetos: {objects.length}</p>{objects.map(o=>{if(o.type==='cristaleira'){const r=calc(o.data,rows,profiles,materials);return <p key={o.id}>{o.name}: {o.data.w} x {o.data.h} mm, custo {brl(r.cost)}, venda {brl(r.sale)}</p>}if(o.type==='closet'){const cl=closetCalc(o.data);return <p key={o.id}>{o.name}: {o.data.w} x {o.data.d} x {o.data.h} mm, perfis {cl.totalProfile.toFixed(2)} m, vidro {cl.glassArea.toFixed(2)} m²</p>}if(o.type==='countertop')return <p key={o.id}>{o.name}: {o.data.w} x {o.data.d} mm, área molhada {o.data.wetW} mm</p>;return <p key={o.id}>{o.name}: {o.data.w} x {o.data.h} mm, vidro {o.data.glass?'sim':'não'}, moldura {o.data.frame?'sim':'não'}</p>})}<div className="status">{colorStatus}</div></div>}
function F(p:{l:string;v:number;f:(e:React.ChangeEvent<HTMLInputElement>)=>void}){return <label>{p.l}<input type="number" value={p.v} onChange={p.f}/></label>}
function Object3D({obj,selected,onSelect,amb,rows,profiles,materials}:{obj:ProjectObject;selected:boolean;onSelect:()=>void;amb:Amb;rows:ParamRow[];profiles:ColorProfile[];materials:ColorMaterial[]}){if(!obj.visible)return null;const common={position:[obj.x/1000,obj.y/1000,obj.z/1000] as [number,number,number],rotation:[0,obj.rotation*Math.PI/180,0] as [number,number,number],onPointerDown:(e:any)=>{e.stopPropagation();onSelect()}};if(obj.type==='window')return <group {...common}><Window3D obj={obj} amb={amb} selected={selected}/></group>;if(obj.type==='countertop')return <group {...common}><Counter3D obj={obj} amb={amb} selected={selected}/></group>;if(obj.type==='closet')return <group {...common}><Closet3D closet={obj.data} selected={selected}/></group>;const r=calc(obj.data,rows,profiles,materials);return <group {...common}><Cab c={obj.data} r={r} selected={selected}/></group>}
function Env3D({amb,selected,onSelect}:{amb:Amb;selected:boolean;onSelect:()=>void}){const w=amb.w/1000,d=amb.d/1000,h=amb.h/1000;return <group onPointerDown={(e:any)=>{e.stopPropagation();onSelect()}}><B p={[0,-.015,0]} z={[w,.03,d]} color={selected?'#4b4b4b':'#383838'}/><gridHelper args={[Math.max(w,d),12]}/>{amb.back&&<B p={[0,h/2,-d/2]} z={[w,h,.04]} color="#d8d8d8" opacity={.72}/>} {amb.left&&<B p={[-w/2,h/2,0]} z={[.04,h,d]} color="#cfcfcf" opacity={.72}/>} {amb.right&&<B p={[w/2,h/2,0]} z={[.04,h,d]} color="#cfcfcf" opacity={.72}/>}</group>}
function Window3D({obj,amb,selected}:{obj:WindowObj;amb:Amb;selected:boolean}){const d=amb.d/1000,w=obj.data.w/1000,h=obj.data.h/1000,y=(obj.data.fromFloor/1000)+h/2,z=-d/2+.035,b=.035;return <group position={[0,y,z]}>{obj.data.glass&&<B p={[0,0,0]} z={[w,h,.018]} color={selected?'#69b7ff':'#77aacc'} opacity={.55}/>} {obj.data.frame&&<><B p={[0,h/2-b/2,.012]} z={[w,b,.035]} color={selected?'#ffcc33':'#222'}/><B p={[0,-h/2+b/2,.012]} z={[w,b,.035]} color={selected?'#ffcc33':'#222'}/><B p={[-w/2+b/2,0,.012]} z={[b,h,.035]} color={selected?'#ffcc33':'#222'}/><B p={[w/2-b/2,0,.012]} z={[b,h,.035]} color={selected?'#ffcc33':'#222'}/></>}</group>}
function Counter3D({obj,amb,selected}:{obj:CounterObj;amb:Amb;selected:boolean}){const c=obj.data,total=c.w/1000,dep=c.d/1000,th=c.thick/1000,wet=Math.min(c.wetW,c.w)/1000,left=(total-wet)/2,y=c.fromFloor/1000+th/2,z=-amb.d/2000+c.depthFromWall/1000+dep/2;return <group position={[0,y,z]}><B p={[-wet/2-left/2,0,0]} z={[left,th,dep]} color={selected?'#c9c9c9':'#aaaaaa'}/><B p={[0,0,0]} z={[wet,th,dep]} color={selected?'#92b5c4':'#7f8f98'}/><B p={[wet/2+left/2,0,0]} z={[left,th,dep]} color={selected?'#c9c9c9':'#aaaaaa'}/>{c.sink&&<B p={[0,th/2+.006,0]} z={[wet*.55,.012,dep*.45]} color="#141414"/>}{c.faucet&&<><B p={[0,th/2+.13,-dep*.18]} z={[.035,.24,.035]} color="#c9c9c9"/><B p={[0,th/2+.23,-dep*.08]} z={[.035,.035,.2]} color="#c9c9c9"/></>}</group>}
function Closet3D({closet,selected}:{closet:ClosetData;selected:boolean}){const w=closet.w/1000,d=closet.d/1000,h=closet.h/1000,m=Math.max(1,closet.modules),mw=w/m,b=.035,rail=.045;return <group position={[0,h/2,0]}><B p={[0,h/2-rail/2,0]} z={[w,rail,d]} color={selected?'#222':'#111'}/><B p={[0,-h/2+rail/2,0]} z={[w,rail,d]} color={selected?'#222':'#111'}/><B p={[0,0,-d/2+rail/2]} z={[w,rail,rail]} color="#111"/>{Array.from({length:m+1}).map((_,i)=><B key={`v${i}`} p={[-w/2+i*mw,0,0]} z={[b,h,d]} color={selected?'#222':'#050505'}/>)}{Array.from({length:m}).map((_,i)=><group key={`mod${i}`} position={[-w/2+mw/2+i*mw,0,0]}>{Array.from({length:closet.shelves}).map((_,j)=><B key={`s${j}`} p={[0,-h/2+(j+1)*h/(closet.shelves+1),0]} z={[mw-.05,.025,d-.08]} color="#b6864a"/>)}{closet.led&&<B p={[0,h/2-.08,-d/2+.06]} z={[mw-.08,.018,.018]} color="#f8e6a5"/>}{closet.doors&&<Door x={0} w={mw-.035} h={h-.08} z={d/2+.025}/>}</group>)}{closet.backGlass&&<B p={[0,0,-d/2+.02]} z={[w-.08,h-.08,.018]} color="#88aacc" opacity={.22}/>}<B p={[-w/2+b/2,0,0]} z={[b,h,d]} color="#111"/><B p={[w/2-b/2,0,0]} z={[b,h,d]} color="#111"/><B p={[-w/2+b,0,0]} z={[.018,h-.1,d-.08]} color="#88aacc" opacity={closet.sideType.includes('9577')?.42:.28}/><B p={[w/2-b,0,0]} z={[.018,h-.1,d-.08]} color="#88aacc" opacity={closet.sideType.includes('9577')?.42:.28}/></group>}
function Cab({c,r,selected}:{c:Config;r:ReturnType<typeof calc>;selected:boolean}){const w=c.w/1000,h=c.h/1000,d=c.d/1000,m=c.mdf/1000,uw=r.uw/1000,uh=r.uh/1000,bw=r.baseW/1000,dw=r.dw/1000,dh=r.dh/1000,side=r.sideGap/1000,gap=r.displayGap/1000;return <group position={[0,h/2,0]}><B p={[-w/2+m/2,0,0]} z={[m,h,d]} color={selected?'#a46f44':'#7a5232'}/><B p={[w/2-m/2,0,0]} z={[m,h,d]} color={selected?'#a46f44':'#7a5232'}/><B p={[0,h/2-m/2,0]} z={[w,m,d]} color="#7a5232"/><B p={[0,-h/2+m/2,0]} z={[w,m,d]} color="#7a5232"/>{Array.from({length:c.shelves}).map((_,i)=><B key={i} p={[0,-uh/2+(i+1)*uh/(c.shelves+1),0]} z={[uw,m,d-m]} color="#8b623e"/>)}{Array.from({length:c.doors}).map((_,i)=><Door key={i} x={-bw/2+side+dw/2+i*(dw+gap)} w={dw} h={dh} z={d/2+0.02}/>)}</group>}
function Door({x,w,h,z}:{x:number;w:number;h:number;z:number}){const b=.035;return <group position={[x,0,z]}><B p={[0,0,0]} z={[w-b*2,h-b*2,.01]} color="#7f5a35" opacity={.45}/><B p={[0,h/2-b/2,.01]} z={[w,b,.03]} color="#050505"/><B p={[0,-h/2+b/2,.01]} z={[w,b,.03]} color="#050505"/><B p={[-w/2+b/2,0,.01]} z={[b,h,.03]} color="#050505"/><B p={[w/2-b/2,0,.01]} z={[b,h,.03]} color="#050505"/></group>}
function B({p,z,color,opacity=1}:{p:[number,number,number];z:[number,number,number];color:string;opacity?:number}){return <mesh position={p}><boxGeometry args={z}/><meshStandardMaterial color={color} transparent={opacity<1} opacity={opacity}/></mesh>}
createRoot(document.getElementById('root') as HTMLElement).render(<React.StrictMode><App/></React.StrictMode>);
