name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"   # a cada 10 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping site
        run: |
          echo "Pinging Render..."
          curl -s https://colorglassfortaleza.com.br > /dev/null

